### PR TITLE
feat: authentication added

### PR DESCRIPTION
**Pull request by vrx29**
Live Preview: https://gimesto-play-git-auth-vrx29.vercel.app/

PR for authentication.

### CODE REVIEW

**Review by partha8 — APPROVED** [review]
The code is very clean, nothing new to suggest. 

I liked how you used cookies instead of local storage, I'll eventually make a note of it and use it in my projects as well. 

Also, in input, when we set ```type='email' ```  and try to input some random things, it will send a warning, right? What extra things does the validateEmail() do?

**Comment by vrx29** [comment]
> The code is very clean, nothing new to suggest.
> 
> I liked how you used cookies instead of local storage, I'll eventually make a note of it and use it in my projects as well.
> 
> Also, in input, when we set `type='email' ` and try to input some random things, it will send a warning, right? What extra things does the validateEmail() do?

@partha8 It sends warning by default I have done that same thing with custom. It is just that it wont show the warning right it will show warning only when user tries to submit the form without proper email

**Review by hsnice16 — APPROVED** [review]
Great work, bro. Couldn't find anything to suggest. UI is fire, and code is good too. Nice job.

**Review by foolhardy21 — APPROVED** [review]
liked the use of `sharedReducer` and `useFetch`. good to go ahead.

**Review by Hamza-777 — APPROVED** [review]
Looks good. Nice UI and code.

**Pull request merged**
